version: "3.9"

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: gomarketplacedb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    ports:
      - 12001:5432
    volumes:
      - ./gomarketplacedb-data:/var/lib/postgresql

volumes:
  db:
