// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
)

type PaymentStatus string

const (
	PaymentStatusSUCCESS  PaymentStatus = "SUCCESS"
	PaymentStatusERROR    PaymentStatus = "ERROR"
	PaymentStatusWAITING  PaymentStatus = "WAITING"
	PaymentStatusCANCELED PaymentStatus = "CANCELED"
)

func (e *PaymentStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PaymentStatus(s)
	case string:
		*e = PaymentStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for PaymentStatus: %T", src)
	}
	return nil
}

type NullPaymentStatus struct {
	PaymentStatus PaymentStatus `json:"payment_status"`
	Valid         bool          `json:"valid"` // Valid is true if PaymentStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPaymentStatus) Scan(value interface{}) error {
	if value == nil {
		ns.PaymentStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PaymentStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPaymentStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PaymentStatus), nil
}

type Category struct {
	CategoryID   int32          `json:"category_id"`
	CategoryName sql.NullString `json:"category_name"`
	ParentID     sql.NullInt32  `json:"parent_id"`
	CreatedAt    sql.NullTime   `json:"created_at"`
	UpdatedAt    sql.NullTime   `json:"updated_at"`
}

type Discount struct {
	DiscountID         int32          `json:"discount_id"`
	ProductID          sql.NullInt32  `json:"product_id"`
	DiscountPercentage sql.NullString `json:"discount_percentage"`
	CreatedAt          sql.NullTime   `json:"created_at"`
	UpdatedAt          sql.NullTime   `json:"updated_at"`
}

type Order struct {
	OrderID   int32         `json:"order_id"`
	OrderDate sql.NullTime  `json:"order_date"`
	BuyerID   sql.NullInt32 `json:"buyer_id"`
	CreatedAt sql.NullTime  `json:"created_at"`
	UpdatedAt sql.NullTime  `json:"updated_at"`
}

type OrderDetail struct {
	DetailID    int32          `json:"detail_id"`
	OrderID     sql.NullInt32  `json:"order_id"`
	ProductID   sql.NullInt32  `json:"product_id"`
	Quantity    sql.NullInt32  `json:"quantity"`
	TotalAmount sql.NullString `json:"total_amount"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
}

type Payment struct {
	PaymentID   int32             `json:"payment_id"`
	OrderID     sql.NullInt32     `json:"order_id"`
	Amount      sql.NullString    `json:"amount"`
	Status      NullPaymentStatus `json:"status"`
	PaymentDate sql.NullTime      `json:"payment_date"`
	CreatedAt   sql.NullTime      `json:"created_at"`
	UpdatedAt   sql.NullTime      `json:"updated_at"`
}

type Product struct {
	ProductID     int32          `json:"product_id"`
	Name          sql.NullString `json:"name"`
	Description   sql.NullString `json:"description"`
	Price         sql.NullString `json:"price"`
	StockQuantity sql.NullInt32  `json:"stock_quantity"`
	SellerID      sql.NullInt32  `json:"seller_id"`
	CategoryID    sql.NullInt32  `json:"category_id"`
	IsActive      sql.NullBool   `json:"is_active"`
	CreatedAt     sql.NullTime   `json:"created_at"`
	UpdatedAt     sql.NullTime   `json:"updated_at"`
}

type Review struct {
	ReviewID  int32          `json:"review_id"`
	ProductID sql.NullInt32  `json:"product_id"`
	UserID    sql.NullInt32  `json:"user_id"`
	Rating    sql.NullInt32  `json:"rating"`
	Comment   sql.NullString `json:"comment"`
	CreatedAt sql.NullTime   `json:"created_at"`
	UpdatedAt sql.NullTime   `json:"updated_at"`
}

type ShippingAddress struct {
	AddressID int32          `json:"address_id"`
	UserID    sql.NullInt32  `json:"user_id"`
	Address   sql.NullString `json:"address"`
	CreatedAt sql.NullTime   `json:"created_at"`
	UpdatedAt sql.NullTime   `json:"updated_at"`
}

type ShoppingCart struct {
	CartID    int32         `json:"cart_id"`
	UserID    sql.NullInt32 `json:"user_id"`
	ProductID sql.NullInt32 `json:"product_id"`
	Quantity  sql.NullInt32 `json:"quantity"`
	CreatedAt sql.NullTime  `json:"created_at"`
	UpdatedAt sql.NullTime  `json:"updated_at"`
}

type User struct {
	UserID    int32          `json:"user_id"`
	FirstName sql.NullString `json:"first_name"`
	LastName  sql.NullString `json:"last_name"`
	SurName   sql.NullString `json:"sur_name"`
	Email     sql.NullString `json:"email"`
	Password  sql.NullString `json:"password"`
	Address   sql.NullString `json:"address"`
	CreatedAt sql.NullTime   `json:"created_at"`
	UpdatedAt sql.NullTime   `json:"updated_at"`
}
