// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"
)

type PaymentStatus string

const (
	PaymentStatusSUCCESS  PaymentStatus = "SUCCESS"
	PaymentStatusERROR    PaymentStatus = "ERROR"
	PaymentStatusWAITING  PaymentStatus = "WAITING"
	PaymentStatusCANCELED PaymentStatus = "CANCELED"
)

func (e *PaymentStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PaymentStatus(s)
	case string:
		*e = PaymentStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for PaymentStatus: %T", src)
	}
	return nil
}

type NullPaymentStatus struct {
	PaymentStatus PaymentStatus `json:"payment_status"`
	Valid         bool          `json:"valid"` // Valid is true if PaymentStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPaymentStatus) Scan(value interface{}) error {
	if value == nil {
		ns.PaymentStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PaymentStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPaymentStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PaymentStatus), nil
}

type Category struct {
	CategoryID   int32         `json:"category_id"`
	CategoryName string        `json:"category_name"`
	ParentID     sql.NullInt32 `json:"parent_id"`
	CreatedAt    time.Time     `json:"created_at"`
	UpdatedAt    sql.NullTime  `json:"updated_at"`
}

type Discount struct {
	DiscountID         int32        `json:"discount_id"`
	ProductID          int32        `json:"product_id"`
	DiscountPercentage string       `json:"discount_percentage"`
	CreatedAt          time.Time    `json:"created_at"`
	UpdatedAt          sql.NullTime `json:"updated_at"`
}

type Order struct {
	OrderID   int32        `json:"order_id"`
	OrderDate time.Time    `json:"order_date"`
	BuyerID   int32        `json:"buyer_id"`
	CreatedAt time.Time    `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}

type OrderDetail struct {
	DetailID    int32        `json:"detail_id"`
	OrderID     int32        `json:"order_id"`
	ProductID   int32        `json:"product_id"`
	Quantity    int32        `json:"quantity"`
	TotalAmount string       `json:"total_amount"`
	CreatedAt   time.Time    `json:"created_at"`
	UpdatedAt   sql.NullTime `json:"updated_at"`
}

type Payment struct {
	PaymentID   int32         `json:"payment_id"`
	OrderID     int32         `json:"order_id"`
	Amount      string        `json:"amount"`
	Status      PaymentStatus `json:"status"`
	PaymentDate time.Time     `json:"payment_date"`
	CreatedAt   time.Time     `json:"created_at"`
	UpdatedAt   sql.NullTime  `json:"updated_at"`
}

type Product struct {
	ProductID     int32        `json:"product_id"`
	Name          string       `json:"name"`
	Description   string       `json:"description"`
	Price         string       `json:"price"`
	StockQuantity int32        `json:"stock_quantity"`
	SellerID      int32        `json:"seller_id"`
	CategoryID    int32        `json:"category_id"`
	IsActive      bool         `json:"is_active"`
	CreatedAt     time.Time    `json:"created_at"`
	UpdatedAt     sql.NullTime `json:"updated_at"`
}

type Review struct {
	ReviewID  int32          `json:"review_id"`
	ProductID int32          `json:"product_id"`
	UserID    int32          `json:"user_id"`
	Rating    int32          `json:"rating"`
	Comment   sql.NullString `json:"comment"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt sql.NullTime   `json:"updated_at"`
}

type ShippingAddress struct {
	AddressID int32        `json:"address_id"`
	UserID    int32        `json:"user_id"`
	Address   string       `json:"address"`
	CreatedAt time.Time    `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}

type ShoppingCart struct {
	CartID    int32        `json:"cart_id"`
	UserID    int32        `json:"user_id"`
	ProductID int32        `json:"product_id"`
	Quantity  int32        `json:"quantity"`
	CreatedAt time.Time    `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}

type User struct {
	UserID    int32        `json:"user_id"`
	FirstName string       `json:"first_name"`
	LastName  string       `json:"last_name"`
	SurName   string       `json:"sur_name"`
	Email     string       `json:"email"`
	Password  string       `json:"password"`
	Address   string       `json:"address"`
	CreatedAt time.Time    `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}
